# Server port
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:collabdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret Key (Should be externalized for production, using a simple string for dev)
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2b8d8cf9c1b3f5c5b4d7981b2123c72b2
jwt.expiration=86400000
